import { Ihale, Danishman, DanishmanYorum, MuteahhitProfil, ReferansProje, MuteahhitYorum } from "./types";

export interface MockTeklif {
  kullanici_adi: string;
  tarih: string;
  tutar?: number;
  muteahhit_id?: string;
}

export const mockIhaleTeklifleri: Record<string, MockTeklif[]> = {
  "1": [
    { kullanici_adi: "Konak İnşaat ve Yapı Ltd. Şti.",       tarih: "2024-01-20T14:23:00Z", tutar: 17200000, muteahhit_id: "m1" },
    { kullanici_adi: "Merkez Yapı A.Ş.",                      tarih: "2024-01-18T09:45:00Z", tutar: 17650000, muteahhit_id: "m2" },
    { kullanici_adi: "Ege Müteahhitlik ve Onarım A.Ş.",       tarih: "2024-01-16T11:30:00Z", tutar: 17900000, muteahhit_id: "m3" },
    { kullanici_adi: "Serkan A. İnşaat",                      tarih: "2024-01-14T16:00:00Z", tutar: 18300000 },
  ],
  "2": [
    { kullanici_adi: "Merkez Yapı A.Ş.",                      tarih: "2024-01-22T08:10:00Z", tutar: 9100000,  muteahhit_id: "m2" },
    { kullanici_adi: "Konak İnşaat ve Yapı Ltd. Şti.",        tarih: "2024-01-20T13:00:00Z", tutar: 9450000,  muteahhit_id: "m1" },
  ],
  "3": [
    { kullanici_adi: "Ege Müteahhitlik ve Onarım A.Ş.",       tarih: "2024-01-21T10:00:00Z", tutar: 31500000, muteahhit_id: "m3" },
    { kullanici_adi: "Konak İnşaat ve Yapı Ltd. Şti.",        tarih: "2024-01-19T15:30:00Z", tutar: 32800000, muteahhit_id: "m1" },
    { kullanici_adi: "Burak K. Yapı",                         tarih: "2024-01-18T12:00:00Z", tutar: 33600000 },
  ],
  "4": [
    { kullanici_adi: "Ege Müteahhitlik ve Onarım A.Ş.",       tarih: "2024-01-28T09:00:00Z", tutar: 3850000,  muteahhit_id: "m3" },
    { kullanici_adi: "Merkez Yapı A.Ş.",                      tarih: "2024-01-25T14:15:00Z", tutar: 3990000,  muteahhit_id: "m2" },
    { kullanici_adi: "Konak İnşaat ve Yapı Ltd. Şti.",        tarih: "2024-01-22T10:30:00Z", tutar: 4050000,  muteahhit_id: "m1" },
  ],
  "6": [
    { kullanici_adi: "Konak İnşaat ve Yapı Ltd. Şti.",        tarih: "2024-01-25T09:00:00Z", tutar: 20500000, muteahhit_id: "m1" },
    { kullanici_adi: "Merkez Yapı A.Ş.",                      tarih: "2024-01-23T14:45:00Z", tutar: 21300000, muteahhit_id: "m2" },
  ],
};

export const mockIhaleler: Ihale[] = [
  {
    id: "1",
    baslik: "Kapalıçarşı Mahallesi Kentsel Dönüşüm Projesi",
    aciklama:
      "İstanbul Fatih ilçesinde riskli yapı statüsündeki 48 konutun yıkılarak yeniden yapılması. Zemin etüdü ve statik proje müteahhide dahildir.",
    kategori: "Kentsel Dönüşüm",
    baslangic_tarihi: "2024-01-10",
    bitis_tarihi: "2024-03-10",
    baslangic_fiyati: 18500000,
    mevcut_teklif: 17200000,
    durum: "aktif",
    kurum: "Fatih Belediyesi",
    sehir: "İstanbul",
    ilce: "Fatih",
    ada_no: "2841",
    parsel_no: "14",
    yapi_insaat_ruhsati: "yok",
    proje: "var",
    goruntulenme_sayisi: 312,
    created_at: "2024-01-10T08:00:00Z",
  },
  {
    id: "2",
    baslik: "Çankaya İlçesi Kat Karşılığı Konut İnşaatı",
    aciklama:
      "Ankara Çankaya'da 1.200 m² arsa üzerine 6 katlı, 24 daireli konut yapımı. Arsa sahibine %45 kat karşılığı verilecektir. Proje ve ruhsat müteahhide aittir.",
    kategori: "Kat Karşılığı",
    baslangic_tarihi: "2024-01-15",
    bitis_tarihi: "2024-02-28",
    baslangic_fiyati: 9800000,
    mevcut_teklif: 9100000,
    durum: "aktif",
    kurum: "Özel Arsa Sahibi",
    sehir: "Ankara",
    ilce: "Çankaya",
    ada_no: "10542",
    parsel_no: "7",
    yapi_insaat_ruhsati: "yok",
    proje: "yok",
    goruntulenme_sayisi: 178,
    yuzolcumu_m2: 1200,
    created_at: "2024-01-15T09:00:00Z",
  },
  {
    id: "3",
    baslik: "Konak Kıyı Konut Kompleksi Yapı İnşaatı",
    aciklama:
      "İzmir Konak ilçesinde 4.800 m² alanda 3 blok, toplam 72 daireli site inşaatı. Betonarme taşıyıcı sistem, dış cephe yalıtımı ve ortak alan düzenlemesi dahil.",
    kategori: "Yapı İnşaat",
    baslangic_tarihi: "2024-01-05",
    bitis_tarihi: "2024-04-05",
    baslangic_fiyati: 34000000,
    mevcut_teklif: 31500000,
    durum: "aktif",
    kurum: "İzmir Konut Yapı Kooperatifi",
    sehir: "İzmir",
    ilce: "Konak",
    ada_no: "5731",
    parsel_no: "3",
    yapi_insaat_ruhsati: "var",
    proje: "var",
    goruntulenme_sayisi: 491,
    yuzolcumu_m2: 4800,
    created_at: "2024-01-05T10:00:00Z",
  },
  {
    id: "4",
    baslik: "Nilüfer Belediyesi Hizmet Binaları Bakım Onarım",
    aciklama:
      "Bursa Nilüfer Belediyesi'ne bağlı 6 hizmet binasının çatı, dış cephe ve iç mekan onarım işleri. İşler detaylı teknik şartname kapsamında yürütülecektir.",
    kategori: "Bakım & Onarım",
    baslangic_tarihi: "2023-12-01",
    bitis_tarihi: "2024-01-31",
    baslangic_fiyati: 4200000,
    mevcut_teklif: 3850000,
    durum: "tamamlandi",
    kurum: "Nilüfer Belediyesi",
    sehir: "Bursa",
    yapi_insaat_ruhsati: "var",
    proje: "yok",
    goruntulenme_sayisi: 247,
    created_at: "2023-12-01T08:00:00Z",
  },
  {
    id: "5",
    baslik: "Mamak İlçesi Riskli Alan Kentsel Dönüşümü",
    aciklama:
      "Ankara Mamak'ta deprem riski taşıyan 120 konutluk alanın kentsel dönüşüm kapsamında yeniden yapılandırılması. TOKİ protokolü çerçevesinde yürütülecektir.",
    kategori: "Kentsel Dönüşüm",
    baslangic_tarihi: "2024-02-01",
    bitis_tarihi: "2024-03-15",
    baslangic_fiyati: 42000000,
    mevcut_teklif: null,
    durum: "beklemede",
    kurum: "Mamak Belediyesi",
    sehir: "Ankara",
    yapi_insaat_ruhsati: "yok",
    proje: "yok",
    goruntulenme_sayisi: 88,
    created_at: "2024-01-20T11:00:00Z",
  },
  {
    id: "6",
    baslik: "Kadıköy Sosyal Konut Projesi Yapı İnşaatı",
    aciklama:
      "İstanbul Kadıköy'de 2.200 m² alan üzerine 8 katlı, 40 daireli sosyal konut inşaatı. Belediye ile protokol kapsamında gerçekleştirilecektir.",
    kategori: "Yapı İnşaat",
    baslangic_tarihi: "2024-01-20",
    bitis_tarihi: "2024-03-20",
    baslangic_fiyati: 22000000,
    mevcut_teklif: 20500000,
    durum: "aktif",
    kurum: "Kadıköy Belediyesi",
    sehir: "İstanbul",
    yapi_insaat_ruhsati: "var",
    proje: "var",
    goruntulenme_sayisi: 203,
    yuzolcumu_m2: 2200,
    created_at: "2024-01-20T08:00:00Z",
  },
];

export const mockDanishmanlar: Danishman[] = [
  {
    id: "d1",
    ad_soyad: "Ahmet Yılmaz",
    uzmanlik_alanlari: ["Kentsel Dönüşüm", "Yapı İnşaat"],
    calistigi_iller: ["İstanbul", "Kocaeli", "Bursa"],
    il: "İstanbul", ilce: "Kadıköy",
    telefon: "0532 111 22 33",
    email: "ahmet.yilmaz@danismanlik.com",
    deneyim_yili: 15,
    biyografi: "İnşaat mühendisi olarak 15 yıldır İstanbul'da kentsel dönüşüm ve yapı denetimi alanında bağımsız danışman olarak görev yapmaktadır. 200'den fazla projeyi başından sonuna denetlemiştir.",
    diploma_sertifika: "İstanbul Teknik Üniversitesi İnşaat Mühendisliği (2009) · Yapı Denetimi Yeterlilik Belgesi · Deprem Güçlendirme Uzmanlık Sertifikası",
    tamamlanan_proje_sayisi: 215,
    aktif_proje_sayisi: 8,
    meslek_odasi: "İnşaat Mühendisleri Odası İstanbul Şubesi",
    sicil_no: "42891",
    created_at: "2023-01-01T00:00:00Z",
  },
  {
    id: "d2",
    ad_soyad: "Fatma Demir",
    uzmanlik_alanlari: ["Kat Karşılığı"],
    calistigi_iller: ["Ankara", "Eskişehir", "Konya"],
    il: "Ankara", ilce: "Çankaya",
    telefon: "0533 222 33 44",
    email: "fatma.demir@denetim.com",
    deneyim_yili: 12,
    biyografi: "Kat karşılığı inşaat sözleşmelerinde uzmanlaşmış bağımsız danışman. Arsa sahibi ve müteahhit arasındaki süreci başından sonuna 3. taraf olarak yönetir. Ankara Üniversitesi İnşaat Mühendisliği mezunu.",
    diploma_sertifika: "Ankara Üniversitesi İnşaat Mühendisliği (2012) · Gayrimenkul Değerleme Uzmanlığı · Yapı Denetim Yeterlilik Belgesi",
    tamamlanan_proje_sayisi: 143,
    aktif_proje_sayisi: 5,
    meslek_odasi: "İnşaat Mühendisleri Odası Ankara Şubesi",
    sicil_no: "31274",
    created_at: "2023-02-01T00:00:00Z",
  },
  {
    id: "d3",
    ad_soyad: "Mehmet Kaya",
    uzmanlik_alanlari: ["Bakım & Onarım", "Yapı İnşaat"],
    calistigi_iller: ["İstanbul", "Sakarya", "Kocaeli"],
    il: "İstanbul", ilce: "Beşiktaş",
    telefon: "0535 333 44 55",
    email: "mehmet.kaya@inspekt.com",
    deneyim_yili: 8,
    biyografi: "Yapı denetim ve bakım-onarım süreçlerinde uzman danışman. Özellikle röleve ve restorasyon projelerinde deneyimli. Her inşaat aşamasında sahada bağımsız gözetim sağlar.",
    diploma_sertifika: "Yıldız Teknik Üniversitesi İnşaat Mühendisliği (2016) · Restorasyon Teknikleri Sertifikası",
    tamamlanan_proje_sayisi: 76,
    aktif_proje_sayisi: 4,
    meslek_odasi: "İnşaat Mühendisleri Odası İstanbul Şubesi",
    sicil_no: "58340",
    created_at: "2023-03-01T00:00:00Z",
  },
  {
    id: "d4",
    ad_soyad: "Zeynep Arslan",
    uzmanlik_alanlari: ["Kentsel Dönüşüm"],
    calistigi_iller: ["İzmir", "Aydın", "Muğla", "Antalya"],
    il: "İzmir", ilce: "Konak",
    telefon: "0536 444 55 66",
    email: "zeynep.arslan@kentsel.com",
    deneyim_yili: 20,
    biyografi: "20 yıllık deneyimiyle İzmir ve Ege Bölgesi'nin en deneyimli kentsel dönüşüm danışmanlarından. Risk tespitinden yeniden yapılanmaya kadar tüm süreci bağımsız olarak denetler.",
    diploma_sertifika: "Dokuz Eylül Üniversitesi İnşaat Mühendisliği (2004) · Kentsel Dönüşüm Uzmanı Sertifikası · Yapı Denetim Yeterlilik Belgesi",
    tamamlanan_proje_sayisi: 310,
    aktif_proje_sayisi: 11,
    meslek_odasi: "İnşaat Mühendisleri Odası İzmir Şubesi",
    sicil_no: "18762",
    created_at: "2023-04-01T00:00:00Z",
  },
  {
    id: "d5",
    ad_soyad: "Ali Çelik",
    uzmanlik_alanlari: ["Kat Karşılığı", "Kentsel Dönüşüm"],
    calistigi_iller: ["İstanbul", "Ankara", "İzmir"],
    il: "İstanbul", ilce: "Maltepe",
    telefon: "0537 555 66 77",
    email: "ali.celik@bagimsizdenetim.com",
    deneyim_yili: 18,
    biyografi: "Kat karşılığı ve kentsel dönüşüm projelerinde 18 yıllık tecrübesiyle arsa sahiplerinin yanında bağımsız danışman olarak yer alır. Projenin her aşamasında hukuki ve teknik kontrol yapar.",
    diploma_sertifika: "İstanbul Üniversitesi İnşaat Mühendisliği (2006) · İnşaat Hukuku Sertifikası · Gayrimenkul Değerleme Uzmanlığı",
    tamamlanan_proje_sayisi: 187,
    aktif_proje_sayisi: 7,
    meslek_odasi: "İnşaat Mühendisleri Odası İstanbul Şubesi",
    sicil_no: "37521",
    created_at: "2023-05-01T00:00:00Z",
  },
  {
    id: "d6",
    ad_soyad: "Ayşe Öztürk",
    uzmanlik_alanlari: ["Yapı İnşaat"],
    calistigi_iller: ["Ankara", "Konya", "Kayseri", "Eskişehir"],
    il: "Ankara", ilce: "Yenimahalle",
    telefon: "0538 666 77 88",
    email: "ayse.ozturk@yapidenetim.com",
    deneyim_yili: 10,
    biyografi: "Yapı inşaatı denetiminde uzmanlaşmış mühendis. Proje aşamasından teslimat kontrolüne kadar her adımda tarafsız danışman olarak görev yapar. Ankara ve İç Anadolu'da aktif.",
    diploma_sertifika: "Orta Doğu Teknik Üniversitesi İnşaat Mühendisliği (2014) · Yapı Denetim Yeterlilik Belgesi",
    tamamlanan_proje_sayisi: 98,
    aktif_proje_sayisi: 6,
    meslek_odasi: "İnşaat Mühendisleri Odası Ankara Şubesi",
    sicil_no: "44912",
    created_at: "2023-06-01T00:00:00Z",
  },
  {
    id: "d7",
    ad_soyad: "Hasan Şahin",
    uzmanlik_alanlari: ["Bakım & Onarım"],
    calistigi_iller: ["Bursa", "Balıkesir", "Sakarya", "Kocaeli"],
    il: "Bursa", ilce: "Nilüfer",
    telefon: "0539 777 88 99",
    email: "hasan.sahin@onarim.com",
    deneyim_yili: 14,
    biyografi: "Bakım ve onarım projelerinde 14 yıldır bağımsız danışmanlık yapan mühendis. Mevcut yapıların güçlendirilmesi, tadilat ve restorasyon süreçlerini denetler. Marmara Bölgesi'nde aktif.",
    diploma_sertifika: "Uludağ Üniversitesi İnşaat Mühendisliği (2010) · Yapı Güçlendirme Uzmanlık Sertifikası · Restorasyon Teknikleri Sertifikası",
    tamamlanan_proje_sayisi: 124,
    aktif_proje_sayisi: 3,
    meslek_odasi: "İnşaat Mühendisleri Odası Bursa Şubesi",
    sicil_no: "52183",
    created_at: "2023-07-01T00:00:00Z",
  },
  {
    id: "d8",
    ad_soyad: "Merve Koç",
    uzmanlik_alanlari: ["Kentsel Dönüşüm", "Kat Karşılığı", "Yapı İnşaat", "Bakım & Onarım"],
    calistigi_iller: ["İstanbul", "Ankara", "İzmir", "Bursa", "Antalya", "Kocaeli"],
    il: "İstanbul", ilce: "Sarıyer",
    telefon: "0541 888 99 00",
    email: "merve.koc@uzmanmufettis.com",
    deneyim_yili: 25,
    biyografi: "25 yıllık kariyerinde tüm inşaat türlerinde bağımsız denetim yapmış, Türkiye'nin en köklü inşaat danışmanlarından. Büyük ölçekli kentsel dönüşüm projelerinde baş danışman olarak görev almış, binlerce yapıyı denetlemiştir.",
    diploma_sertifika: "Boğaziçi Üniversitesi İnşaat Mühendisliği (1999) · Kentsel Dönüşüm Uzmanı · Deprem Güçlendirme Uzmanlığı · Yapı Denetim Yeterlilik Belgesi",
    tamamlanan_proje_sayisi: 520,
    aktif_proje_sayisi: 14,
    meslek_odasi: "İnşaat Mühendisleri Odası İstanbul Şubesi",
    sicil_no: "11047",
    created_at: "2023-08-01T00:00:00Z",
  },
];

export const mockMuteahhitler: MuteahhitProfil[] = [
  {
    id: "m1",
    kullanici_id: "m1",
    firma_adi: "Konak İnşaat ve Yapı Ltd. Şti.",
    kurulus_yili: 2005,
    calistigi_iller: ["İstanbul", "Kocaeli", "Bursa", "Sakarya"],
    uzmanlik_alanlari: ["Kentsel Dönüşüm", "Yapı İnşaat"],
    lisans_no: "YM-2005-1874",
    sicil_no: "34-MÜT-8821",
    telefon: "0212 444 55 66",
    email: "info@konakinsaat.com",
    aciklama: "2005 yılında kurulan Konak İnşaat, İstanbul ve Marmara Bölgesi'nde 20 yılı aşkın tecrübesiyle konut, konut kompleksi ve kentsel dönüşüm alanlarında hizmet vermektedir. ISO 9001 kalite belgeli firmamız, teslim ettiği her projeyi zamanında ve bütçe dahilinde tamamlamayı ilke edinmiştir.",
    foto_url: undefined,
    sertifika_bilgisi: "ISO 9001:2015 Kalite Yönetim Sistemi · TSE Yapı Malzemeleri Uygunluk Belgesi · Çevre ve Şehircilik Bakanlığı Müteahhitlik Yeterlik Belgesi (A Sınıfı)",
    tamamlanan_proje_sayisi: 47,
    kazanilan_ihale_sayisi: 31,
    aktif_ihale_sayisi: 3,
    created_at: "2023-01-15T00:00:00Z",
  },
  {
    id: "m2",
    kullanici_id: "m2",
    firma_adi: "Merkez Yapı A.Ş.",
    kurulus_yili: 2010,
    calistigi_iller: ["Ankara", "Konya", "Kayseri", "Eskişehir"],
    uzmanlik_alanlari: ["Kat Karşılığı", "Kentsel Dönüşüm"],
    lisans_no: "YM-2010-3312",
    sicil_no: "06-MÜT-4450",
    telefon: "0312 555 66 77",
    email: "info@merkezyapi.com.tr",
    aciklama: "Ankara merkezli Merkez Yapı A.Ş., özellikle kat karşılığı inşaat ve kentsel dönüşüm projelerinde uzmanlaşmış bir yapı şirketidir. Arsa sahiplerine şeffaf sözleşme yönetimi, yerinde teknik ekip ve taahhüt güvencesi sunmaktayız.",
    foto_url: undefined,
    sertifika_bilgisi: "Çevre ve Şehircilik Bakanlığı Müteahhitlik Yeterlik Belgesi (B Sınıfı) · Ankara Ticaret Odası Üye Belgesi · OHSAS 18001 İş Sağlığı ve Güvenliği Belgesi",
    tamamlanan_proje_sayisi: 28,
    kazanilan_ihale_sayisi: 19,
    aktif_ihale_sayisi: 2,
    created_at: "2023-03-10T00:00:00Z",
  },
  {
    id: "m3",
    kullanici_id: "m3",
    firma_adi: "Ege Müteahhitlik ve Onarım A.Ş.",
    kurulus_yili: 1998,
    calistigi_iller: ["İzmir", "Aydın", "Muğla", "Manisa", "Denizli"],
    uzmanlik_alanlari: ["Yapı İnşaat", "Bakım & Onarım"],
    lisans_no: "YM-1998-0543",
    sicil_no: "35-MÜT-1196",
    telefon: "0232 333 44 55",
    email: "ofis@egememuteahhit.com",
    aciklama: "İzmir merkezli Ege Müteahhitlik, 1998'den bu yana Ege Bölgesi'nde yapı inşaatı ve bakım-onarım projelerinde kesintisiz hizmet vermektedir. 25 yılı aşkın deneyimimizle kamu kurumları ve özel sektöre hizmet veren firmamız, güçlü mühendislik kadrosu ve modern makine parkuruyla öne çıkmaktadır.",
    foto_url: undefined,
    sertifika_bilgisi: "Çevre ve Şehircilik Bakanlığı Müteahhitlik Yeterlik Belgesi (A Sınıfı) · ISO 14001:2015 Çevre Yönetim Sistemi · TSE Hizmet Yeterlilik Belgesi",
    tamamlanan_proje_sayisi: 83,
    kazanilan_ihale_sayisi: 62,
    aktif_ihale_sayisi: 5,
    created_at: "2023-05-20T00:00:00Z",
  },
];

export const mockReferansProjeler: ReferansProje[] = [
  {
    id: "rp1",
    muteahhit_id: "m1",
    proje_adi: "Ataşehir Kentsel Dönüşüm Projesi",
    konum: "İstanbul / Ataşehir",
    yil: 2022,
    tur: "Kentsel Dönüşüm",
    aciklama: "64 daireli riskli yapı alanının yıkılıp yeniden yapılması. 18 ay içinde teslim edildi.",
    created_at: "2023-01-15T00:00:00Z",
  },
  {
    id: "rp2",
    muteahhit_id: "m1",
    proje_adi: "Kartal Premium Konut Sitesi",
    konum: "İstanbul / Kartal",
    yil: 2021,
    tur: "Yapı İnşaat",
    aciklama: "3 blok, 96 daireli kapalı site. Sosyal tesisler ve otopark dahil.",
    created_at: "2023-01-15T00:00:00Z",
  },
  {
    id: "rp3",
    muteahhit_id: "m1",
    proje_adi: "Üsküdar Kamu Yapıları Yenileme",
    konum: "İstanbul / Üsküdar",
    yil: 2023,
    tur: "Kentsel Dönüşüm",
    aciklama: "Belediyeye ait 4 yapının güçlendirilmesi ve yenilenmesi.",
    created_at: "2023-01-15T00:00:00Z",
  },
  {
    id: "rp4",
    muteahhit_id: "m2",
    proje_adi: "Mamak Dönüşüm Alanı — 1. Etap",
    konum: "Ankara / Mamak",
    yil: 2023,
    tur: "Kentsel Dönüşüm",
    aciklama: "120 konutluk riskli alanın TOKİ protokolü kapsamında yeniden yapılanması.",
    created_at: "2023-03-10T00:00:00Z",
  },
  {
    id: "rp5",
    muteahhit_id: "m2",
    proje_adi: "Çankaya Kat Karşılığı Konut Projesi",
    konum: "Ankara / Çankaya",
    yil: 2022,
    tur: "Kat Karşılığı",
    aciklama: "1.200 m² arsa üzerine 6 katlı 24 daireli konut. Arsa sahiplerine %45 kat karşılığı.",
    created_at: "2023-03-10T00:00:00Z",
  },
  {
    id: "rp6",
    muteahhit_id: "m3",
    proje_adi: "Konak Kıyı Konut Kompleksi",
    konum: "İzmir / Konak",
    yil: 2022,
    tur: "Yapı İnşaat",
    aciklama: "4.800 m² alanda 3 blok, 72 daireli konut kompleksi.",
    created_at: "2023-05-20T00:00:00Z",
  },
  {
    id: "rp7",
    muteahhit_id: "m3",
    proje_adi: "Bornova Belediyesi Hizmet Binaları Onarım",
    konum: "İzmir / Bornova",
    yil: 2023,
    tur: "Bakım & Onarım",
    aciklama: "Belediyeye ait 8 hizmet binasının çatı ve cephe yenileme çalışmaları.",
    created_at: "2023-05-20T00:00:00Z",
  },
  {
    id: "rp8",
    muteahhit_id: "m3",
    proje_adi: "Karşıyaka Karma Kullanım Yapısı",
    konum: "İzmir / Karşıyaka",
    yil: 2021,
    tur: "Yapı İnşaat",
    aciklama: "Zemin katta ticari, üst katlarda konut bulunan 10 katlı karma yapı.",
    created_at: "2023-05-20T00:00:00Z",
  },
];

export const mockMuteahhitYorumlar: MuteahhitYorum[] = [
  { id: "my1", muteahhit_id: "m1", kullanici_adi: "Serhat K.", puan: 5, yorum_metni: "Ataşehir projemizde inanılmaz bir hizmet aldık. Hem zamanında teslim ettiler hem de bütçeyi aşmadılar. Çok memnunum.", created_at: "2024-01-10T10:00:00Z" },
  { id: "my2", muteahhit_id: "m1", kullanici_adi: "Nurdan A.", puan: 4, yorum_metni: "Genel olarak memnunum. İletişim biraz geç sağlandı ama işçilik kalitesi çok iyiydi. Tavsiye ederim.", created_at: "2023-11-05T14:00:00Z" },
  { id: "my3", muteahhit_id: "m1", kullanici_adi: "Emre Y.", puan: 5, yorum_metni: "Kentsel dönüşüm sürecinde bize rehberlik ettiler. Sözleşme aşamasından teslime kadar her şey çok düzenliydi.", created_at: "2023-09-20T09:00:00Z" },
  { id: "my4", muteahhit_id: "m2", kullanici_adi: "Derya Ö.", puan: 5, yorum_metni: "Kat karşılığı projemizde tam anlamıyla güvendik. Tüm süreci şeffaf yönettiler, hiçbir sürpriz olmadı.", created_at: "2024-02-01T11:00:00Z" },
  { id: "my5", muteahhit_id: "m2", kullanici_adi: "Cemal T.", puan: 4, yorum_metni: "Biraz yavaş ilerledi ama kaliteden ödün vermediler. Bitişi biraz gecikti ama sonuçtan memnunum.", created_at: "2024-01-15T16:00:00Z" },
  { id: "my6", muteahhit_id: "m3", kullanici_adi: "Filiz M.", puan: 5, yorum_metni: "25 yıllık tecrübe gerçekten fark yaratıyor. İzmir'deki en güvenilir müteahhitlerden biri. Kesinlikle öneririm.", created_at: "2024-02-15T13:00:00Z" },
  { id: "my7", muteahhit_id: "m3", kullanici_adi: "Uğur B.", puan: 5, yorum_metni: "Bakım-onarım işimizi çok profesyonelce hallettiler. Ekip sahada aktifti, işçilik çok kaliteliydi.", created_at: "2024-01-28T10:00:00Z" },
  { id: "my8", muteahhit_id: "m3", kullanici_adi: "Hande K.", puan: 4, yorum_metni: "İzmir'de güvenilir iş ortağı bulmak zor. Ege Müteahhitlik bu konuda gerçekten güvenilir bir firma.", created_at: "2023-12-10T09:30:00Z" },
];

export const mockYorumlar: DanishmanYorum[] = [
  { id: "y1", danishman_id: "d1", kullanici_adi: "Mehmet A.", puan: 5, yorum_metni: "Projemizin her aşamasında titizlikle çalıştı. Temel döküm aşamasında tespit ettiği sorunlar sayesinde büyük problemlerin önüne geçtik. Kesinlikle tavsiye ediyorum.", created_at: "2024-01-15T10:00:00Z" },
  { id: "y2", danishman_id: "d1", kullanici_adi: "Selin K.", puan: 4, yorum_metni: "Çok tecrübeli ve bilgili bir danışman. Raporları oldukça detaylıydı. Zaman zaman ulaşmak güçleşti ama genel olarak memnun kaldık.", created_at: "2023-11-20T14:30:00Z" },
  { id: "y3", danishman_id: "d1", kullanici_adi: "Hüseyin D.", puan: 5, yorum_metni: "Kentsel dönüşüm sürecinde bize çok yardımcı oldu. Müteahhidin yapmadığı işleri tespit etti ve düzelttirdi. Haklarımızı sonuna kadar korudu.", created_at: "2023-09-05T09:15:00Z" },
  { id: "y4", danishman_id: "d2", kullanici_adi: "Ahmet B.", puan: 5, yorum_metni: "Kat karşılığı sözleşmemizde haklarımızı sonuna kadar korudu. Müteahhidle yaşanan anlaşmazlıkta teknik desteğini de eksiksiz verdi.", created_at: "2024-02-10T11:00:00Z" },
  { id: "y5", danishman_id: "d2", kullanici_adi: "Canan T.", puan: 4, yorum_metni: "İnşaat sürecinde sürekli takip etti, eksiklikleri anında bildirdi. Güvenilir ve dürüst bir danışman.", created_at: "2024-01-05T16:45:00Z" },
  { id: "y6", danishman_id: "d4", kullanici_adi: "Kemal Ş.", puan: 5, yorum_metni: "20 yıllık deneyimi sahada hissediliyor. İzmir'deki projemizi denetletti, hiçbir eksiği gözden kaçırmadı. Profesyonelliği için teşekkür ederiz.", created_at: "2024-02-20T13:00:00Z" },
  { id: "y7", danishman_id: "d8", kullanici_adi: "İbrahim Y.", puan: 5, yorum_metni: "Türkiye'nin en iyi danışmanlarından biri. 25 yıllık tecrübe gerçekten fark yaratıyor. Büyük projemizde inanılmaz bir hizmet aldık.", created_at: "2024-03-01T10:30:00Z" },
  { id: "y8", danishman_id: "d8", kullanici_adi: "Elif M.", puan: 5, yorum_metni: "Büyük projemizin baş danışmanı olarak mükemmel bir iş çıkardı. Raporları çok kapsamlıydı, her aşamada sahada aktifti. Kesinlikle tavsiye ediyorum.", created_at: "2024-02-15T09:00:00Z" },
  { id: "y9", danishman_id: "d5", kullanici_adi: "Burak Ö.", puan: 5, yorum_metni: "Kat karşılığı projemizde Ali Bey'in desteği paha biçilmezdi. Hem teknik hem hukuki konularda çok yetkin.", created_at: "2024-01-28T11:00:00Z" },
  { id: "y10", danishman_id: "d5", kullanici_adi: "Naciye A.", puan: 4, yorum_metni: "Genel olarak memnunum. Zaman zaman yoğunluğu nedeniyle geç yanıt verdi ama yaptığı denetim kaliteliydi.", created_at: "2024-01-10T09:30:00Z" },
];
